[workspace]
members = ["rust-lwb", "rust-lwb-bootstrap", "rust-lwb-macros", "rust-lwb-tests", "examples/simple-typed-language", "lwb-parser"]
default-members = ["rust-lwb", "rust-lwb-tests", "examples/simple-typed-language", "lwb-parser"]
